// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIKtl3aEcEirmk0vjkANzcY6Xet7MgCSY',
    appId: '1:390772207496:web:3fad95bf840bd02d29943d',
    messagingSenderId: '390772207496',
    projectId: 'erbe-wim',
    authDomain: 'erbe-wim.firebaseapp.com',
    storageBucket: 'erbe-wim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzMHIUmFigi5vFxsRdyKhWlsXbo68IEoE',
    appId: '1:390772207496:android:f373e3c19501654929943d',
    messagingSenderId: '390772207496',
    projectId: 'erbe-wim',
    storageBucket: 'erbe-wim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqehPjI5-jetuBi8t1-Bz_a2E0i7ng3cM',
    appId: '1:390772207496:ios:4b8465c2e78733ce29943d',
    messagingSenderId: '390772207496',
    projectId: 'erbe-wim',
    storageBucket: 'erbe-wim.appspot.com',
    iosClientId: '390772207496-asuds7tj6gcf2nuj3v3rf789a6gi7o08.apps.googleusercontent.com',
    iosBundleId: 'com.example.erbe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqehPjI5-jetuBi8t1-Bz_a2E0i7ng3cM',
    appId: '1:390772207496:ios:4b8465c2e78733ce29943d',
    messagingSenderId: '390772207496',
    projectId: 'erbe-wim',
    storageBucket: 'erbe-wim.appspot.com',
    iosClientId: '390772207496-asuds7tj6gcf2nuj3v3rf789a6gi7o08.apps.googleusercontent.com',
    iosBundleId: 'com.example.erbe',
  );
}
